### ISSUE TITLE
Heading of Main Page

### ISSUE THREAD

**Issue by Priiyaa** [niloysikdar/Get-Set-Go#1]
I would like to work on the **main page of the site first i.e Get-Set-Go**. As of now, I would like to _**decorate the heading**_. Can you please tell me a little more about the theme?

**Comment by niloysikdar** [comment]
Yeah sure @Priiyaa , join us today at 9 PM and we will discuss important things about this project.
Also, feel free to drop a message on the discord channel for better communication.

Closing this issue for now.
