### ISSUE TITLE
feat: landing page (code)

### ISSUE THREAD

**Issue by niloysikdar** [niloysikdar/Get-Set-Go#5]
Need to create the landing page using HTML and CSS (don't use any CSS libraries or frameworks)
Design: https://imgur.com/a/AFQR3HL

**Comment by AtriSukul1508** [comment]
I would like to work on this issue under JWOC

**Comment by tanya-gupta25** [comment]
I want to work on this issue under JWOC

**Comment by niloysikdar** [comment]
Assigned you @AtriSukul1508 
I will create a few new issues, please have a look at them @tanya-gupta25
