### ISSUE TITLE
feat:Add a gallery section in the home page

### ISSUE THREAD

**Issue by AtriSukul1508** [niloysikdar/Get-Set-Go#8]

**Comment by AtriSukul1508** [comment]
I would like to work on this issue under JWOC

**Comment by codervivek5** [comment]
I would like to work on this issue under JWOC.plz assign it me.

**Comment by niloysikdar** [comment]
Hi @codervivek5 , since @AtriSukul1508 is working on this issue, do you want to take up new issues?

**Comment by codervivek5** [comment]
> Hi @codervivek5 , since @AtriSukul1508 is working on this issue, do you want to take up new issues?

yes I want...

**Comment by niloysikdar** [comment]
Great, let me open new issues for you
