### ISSUE TITLE
feat: location page

### ISSUE THREAD

**Issue by niloysikdar** [niloysikdar/Get-Set-Go#9]
Since we are going to showcase different data and categories of different places, we need a single page for the locations and then we can modify data dynamically according to the location using JavaScript.

Good UI UX will be really appreciated.

**Comment by niloysikdar** [comment]
@codervivek5 do you want to work on this issue ?

**Comment by codervivek5** [comment]
what we havedo for it ?

**Comment by tanya-gupta25** [comment]
I want to work on this issue under JWOC.

**Comment by codervivek5** [comment]
> @codervivek5 do you want to work on this issue ?

Sure...i want to work on it

**Comment by niloysikdar** [comment]
You can easily figure it out if you have an idea of the project. If not, then feel free to ping me on discord and we can connect on the voice channel tomorrow.

@tanya-gupta25 do you need help or an idea to solve this issue?

**Comment by codervivek5** [comment]
> @codervivek5 You can easily figure it out if you have an idea of the project. If not, then feel free to ping me on discord and we can connect on the voice channel tomorrow.
> 
> @tanya-gupta25 do you need help or an idea to solve this issue?

Ok i will connect with you in voice channel tomorrow for some queries

**Comment by AtriSukul1508** [comment]
I would like to work on this issue under JWOC
